name: Docker

on:
  push:
    branches:
      # Publish `main` branch as Docker `latest` image.
      - main
    tags:
      - '*'
    paths-ignore:
      - README.md
      - LICENSE.md
      - CHANGELOG.md
      - RELEASENOTES.md
      - docs/**/*
      - templates/**/*
  pull_request:
    branches:
      # Only trigger for PRs against `main` branch.
      - main
    paths-ignore:
      - README.md
      - LICENSE.md
      - CHANGELOG.md
      - RELEASENOTES.md
      - docs/**/*
      - templates/**/*

jobs:
  dockerize:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: 'dependabot-azure-devops'

    steps:
      - uses: actions/checkout@v2

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

      - name: Build image
        run: |
          docker build \
          -f src/Dockerfile \
          -t "$IMAGE_NAME" \
          src

      - name: Log into registry (GitHub)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image to GitHub packages
        run: |
          IMAGE_ID="docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME"
          docker tag "$IMAGE_NAME" $IMAGE_ID:${{ steps.gitversion.outputs.fullSemVer }}
          docker push "$IMAGE_ID:${{ steps.gitversion.outputs.fullSemVer }}"

      - name: Log into registry (Docker Hub)
        if: startsWith(github.ref, 'refs/tags')
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image to Docker Hub
        if: startsWith(github.ref, 'refs/tags')
        run: |
          docker tag "$IMAGE_NAME" "tingle/$IMAGE_NAME:${{ steps.gitversion.outputs.fullSemVer }}"
          docker push "tingle/$IMAGE_NAME:${{ steps.gitversion.outputs.fullSemVer }}"
