name: Extension

on:
  push:
    branches:
      - main # TODO: remove this after testing is complete
    tags:
      - '*'
    paths:
      - "src/extension/**"
      - ".github/workflows/extension.yml"
  pull_request:
    branches:
      # Only trigger for PRs against `main` branch.
      - main
    paths:
      - "src/extension/**"
      - ".github/workflows/extension.yml"

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Required for GitVersion

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Install tfx-cli
      run: npm install -g tfx-cli@0.8.3

    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1.0
      with:
        files: '["${{ github.workspace }}/src/extension/overrides.json"]'

    - name: Create Extension
      run: >
        tfx extension create
        --root src/extension
        --manifest-globs vss-extension.json
        --output-path $GITHUB_WORKSPACE/drop
        --json5
        --overrides-file $GITHUB_WORKSPACE/src/extension/overrides.json

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}/drop/*
        name: drop

  Publish:
    runs-on: ubuntu-latest
    needs: [ Build ]
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: drop

    - name: Publish to market place
      run: |
        echo "Work in progress"
